export {default as Actors} from './Actors/Actors'
export {default as Profile} from './Profile/Profile'
export {default as Movies} from './Movies/Movies'
export {default as Moviesinformation} from './Moviesinformation/Moviesinformation'
export {default as Navbar} from './Navbar/Navbar'
